# Скрипт для отбора данных из датасета FMA для дальнейшей кластеризации 
https://github.com/mdeff/fma
# Код кластеризация для данного датасета в `clustering_FMA.ipynb`

In [3]:

import pandas as pd

In [4]:
tracks = pd.read_csv(r'C:\Users\user\Downloads\fma_metadata\tracks.csv',index_col=0, header=[1])

C:\Users\user\AppData\Local\Temp\ipykernel_28568\974950279.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  tracks = pd.read_csv(r'C:\Users\user\Downloads\fma_metadata\tracks.csv',index_col=0, header=[1])

In [5]:
tracks.shape

(106575, 52)

In [6]:
tracks

,comments,date_created,date_released,engineer,favorites,id,information,listens,producer,tags,...,information.1,interest,language_code,license,listens.1,lyricist,number,publisher,tags.2,title.1
track_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4.0,1.0,<p></p>,6073.0,NaN,[],...,NaN,4656.0,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1293.0,NaN,3.0,NaN,[],Food
3,0.0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4.0,1.0,<p></p>,6073.0,NaN,[],...,NaN,1470.0,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,514.0,NaN,4.0,NaN,[],Electric Ave
5,0.0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4.0,1.0,<p></p>,6073.0,NaN,[],...,NaN,1933.0,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1151.0,NaN,6.0,NaN,[],This World
10,0.0,2008-11-26 01:45:08,2008-02-06 00:00:00,NaN,4.0,6.0,NaN,47632.0,NaN,[],...,NaN,54881.0,en,Attribution-NonCommercial-NoDerivatives (aka M...,50135.0,NaN,1.0,NaN,[],Freeway
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155316,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,[],...,NaN,122.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,102.0,NaN,3.0,NaN,[],The Auger
155317,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,[],...,NaN,194.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,165.0,NaN,4.0,NaN,[],Let's Skin Ruby
155318,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,[],...,NaN,214.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,168.0,NaN,6.0,NaN,[],My House Smells Like Kim Deal/Pulp
155319,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,[],...,NaN,336.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,294.0,NaN,5.0,NaN,[],The Man With Two Mouths
155320,0.0,2017-03-26 16:22:18,2017-03-26 00:00:00,NaN,1.0,22906.0,NaN,7481.0,NaN,"['ballad', 'epic', 'rockabilly', 'curse', 'hex...",...,NaN,972.0,NaN,Attribution-NonCommercial,705.0,NaN,7.0,NaN,"['ballad', 'epic', 'rockabilly', 'curse', 'hex...",Another Trick Up My Sleeve (Instrumental)

In [7]:
columnns = ['favorites','id', 'listens','tracks','comments.1','latitude','longitude','bit_rate','duration','interest']

In [8]:
tracks.reset_index(inplace=True)
tracks

,index,comments,date_created,date_released,engineer,favorites,id,information,listens,producer,...,information.1,interest,language_code,license,listens.1,lyricist,number,publisher,tags.2,title.1
0,track_id,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,0.0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4.0,1.0,<p></p>,6073.0,NaN,...,NaN,4656.0,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1293.0,NaN,3.0,NaN,[],Food
2,3,0.0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4.0,1.0,<p></p>,6073.0,NaN,...,NaN,1470.0,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,514.0,NaN,4.0,NaN,[],Electric Ave
3,5,0.0,2008-11-26 01:44:45,2009-01-05 00:00:00,NaN,4.0,1.0,<p></p>,6073.0,NaN,...,NaN,1933.0,en,Attribution-NonCommercial-ShareAlike 3.0 Inter...,1151.0,NaN,6.0,NaN,[],This World
4,10,0.0,2008-11-26 01:45:08,2008-02-06 00:00:00,NaN,4.0,6.0,NaN,47632.0,NaN,...,NaN,54881.0,en,Attribution-NonCommercial-NoDerivatives (aka M...,50135.0,NaN,1.0,NaN,[],Freeway
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106570,155316,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,...,NaN,122.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,102.0,NaN,3.0,NaN,[],The Auger
106571,155317,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,...,NaN,194.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,165.0,NaN,4.0,NaN,[],Let's Skin Ruby
106572,155318,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,...,NaN,214.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,168.0,NaN,6.0,NaN,[],My House Smells Like Kim Deal/Pulp
106573,155319,0.0,2017-03-30 15:20:35,2017-02-17 00:00:00,NaN,0.0,22940.0,"<p>A live performance at Monty Hall on Feb 17,...",1506.0,Monty Hall,...,NaN,336.0,NaN,Creative Commons Attribution-NonCommercial-NoD...,294.0,NaN,5.0,NaN,[],The Man With Two Mouths
106574,155320,0.0,2017-03-26 16:22:18,2017-03-26 00:00:00,NaN,1.0,22906.0,NaN,7481.0,NaN,...,NaN,972.0,NaN,Attribution-NonCommercial,705.0,NaN,7.0,NaN,"['ballad', 'epic', 'rockabilly', 'curse', 'hex...",Another Trick Up My Sleeve (Instrumental)

In [9]:
tracks = tracks[columnns][1:]

In [10]:
tracks.shape

(106574, 10)

In [11]:
tracks = tracks.dropna(how='any')

In [12]:
tracks.shape

(44544, 10)

In [13]:
tracks = tracks.rename({'comments.1':'comments'}, axis='columns')
tracks

,favorites,id,listens,tracks,comments,latitude,longitude,bit_rate,duration,interest
1,4.0,1.0,6073.0,7.0,0.0,40.058324,-74.405661,256000.0,168.0,4656.0
2,4.0,1.0,6073.0,7.0,0.0,40.058324,-74.405661,256000.0,237.0,1470.0
3,4.0,1.0,6073.0,7.0,0.0,40.058324,-74.405661,256000.0,206.0,1933.0
5,2.0,4.0,2710.0,13.0,2.0,51.895927,0.891874,256000.0,311.0,978.0
6,2.0,4.0,2710.0,13.0,2.0,51.895927,0.891874,256000.0,181.0,1060.0
...,...,...,...,...,...,...,...,...,...,...
106380,-1.0,-1.0,-1.0,-1.0,0.0,45.512303,-73.554431,160000.0,379.0,609.0
106381,-1.0,-1.0,-1.0,-1.0,0.0,45.512303,-73.554431,160000.0,299.0,980.0
106382,-1.0,-1.0,-1.0,-1.0,7.0,46.053219,8.986100,192000.0,269.0,41.0
106410,0.0,20610.0,31847.0,6.0,3.0,35.670479,139.740921,256000.0,193.0,1912.0
106520,-1.0,-1.0,-1.0,-1.0,2.0,52.152355,5.292970,320000.0,104.0,964.0

In [14]:
tracks.info()

<class 'pandas.core.frame.DataFrame'>
Index: 44544 entries, 1 to 106520
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   favorites  44544 non-null  float64
 1   id         44544 non-null  float64
 2   listens    44544 non-null  float64
 3   tracks     44544 non-null  float64
 4   comments   44544 non-null  float64
 5   latitude   44544 non-null  float64
 6   longitude  44544 non-null  float64
 7   bit_rate   44544 non-null  float64
 8   duration   44544 non-null  float64
 9   interest   44544 non-null  float64
dtypes: float64(10)
memory usage: 3.7 MB

In [15]:
tracks.to_csv(r'D:\Artem\Magistrature\1_sem\intellg_systems_and_techno\labs\datasets\FMA\tracks.csv')